filebeat:
  build: .
  restart: unless-stopped
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock
  environment:
   - ELASTICSEARCH_HOST=localhost
   - ELASTICSEARCH_PORT=9200
   - SHIPPER_NAME=test
